use std::path::Path;

use anyhow::Result;

use crate::config::ContextlintConfig;
use crate::discovery::discover_context_files;
use crate::parser::parse_context_file;

pub fn generate_agents(root: &Path, output: &Path, from: Option<&str>) -> Result<()> {
    let source_paths = if let Some(from) = from {
        from.split(',')
            .map(|part| root.join(part.trim()))
            .filter(|path| path.exists())
            .collect::<Vec<_>>()
    } else {
        discover_context_files(root, &ContextlintConfig::default(), &[], &[])?
    };

    let mut files = Vec::new();
    for path in &source_paths {
        files.push(parse_context_file(root, path)?);
    }

    let mut out = String::new();
    out.push_str("# Agent Instructions\n\n");
    out.push_str("Generated by ContextLint. Review before replacing existing agent files.\n\n");

    out.push_str("## Project Overview\n\n");
    out.push_str(&project_overview(root, &files));
    out.push_str("\n\n");

    out.push_str("## Development Commands\n\n");
    let commands = infer_commands(root);
    if commands.is_empty() {
        out.push_str("- Add install, test, build, and lint commands here.\n");
    } else {
        for command in commands {
            out.push_str(&format!("- {}: `{}`\n", command.0, command.1));
        }
    }
    out.push('\n');

    out.push_str("## Development Rules\n\n");
    let rules = extract_rules(&files);
    if rules.is_empty() {
        out.push_str("- Follow existing project conventions.\n");
        out.push_str("- Run relevant tests before final response.\n");
        out.push_str("- Ask before destructive file or database changes.\n");
    } else {
        for rule in rules.into_iter().take(20) {
            out.push_str(&format!("- {}\n", rule));
        }
    }
    out.push('\n');

    out.push_str("## Context Files\n\n");
    for file in &files {
        out.push_str(&format!(
            "- `{}` — {} estimated tokens\n",
            file.path, file.estimated_tokens
        ));
    }

    let output_path = if output.is_absolute() {
        output.to_path_buf()
    } else {
        root.join(output)
    };
    std::fs::write(output_path, out)?;
    Ok(())
}

fn project_overview(root: &Path, files: &[crate::model::ContextFile]) -> String {
    if let Some(readme) = files.iter().find(|file| file.path == "README.md") {
        let mut lines = Vec::new();
        for line in readme.content.lines() {
            let trimmed = line.trim();
            if trimmed.is_empty() || trimmed.starts_with('#') || trimmed.starts_with("```") {
                if !lines.is_empty() {
                    break;
                }
                continue;
            }
            lines.push(trimmed);
            if lines.join(" ").chars().count() > 500 {
                break;
            }
        }
        let overview = lines.join(" ");
        if !overview.is_empty() {
            return overview;
        }
    }

    let project = root
        .file_name()
        .and_then(|name| name.to_str())
        .unwrap_or("this project");
    format!("{project} project. Keep context short, accurate, relevant, safe, and useful.")
}

fn infer_commands(root: &Path) -> Vec<(String, String)> {
    let mut commands = Vec::new();

    if root.join("Cargo.toml").exists() {
        commands.push(("Check".into(), "cargo check".into()));
        commands.push(("Test".into(), "cargo test".into()));
        commands.push(("Build".into(), "cargo build".into()));
    }

    let package_json = root.join("package.json");
    if let Ok(content) = std::fs::read_to_string(package_json) {
        if let Ok(json) = serde_json::from_str::<serde_json::Value>(&content) {
            if let Some(scripts) = json.get("scripts").and_then(|value| value.as_object()) {
                for name in ["dev", "test", "lint", "build"] {
                    if scripts.contains_key(name) {
                        commands.push((capitalize(name), format!("npm run {name}")));
                    }
                }
            }
        }
    }

    commands
}

fn extract_rules(files: &[crate::model::ContextFile]) -> Vec<String> {
    let mut rules = Vec::new();
    for file in files {
        for line in file.content.lines() {
            let trimmed = line.trim();
            if !(trimmed.starts_with("- ") || trimmed.starts_with("* ")) {
                continue;
            }
            let rule = trimmed.trim_start_matches(['-', '*']).trim();
            let lower = rule.to_lowercase();
            let actionable = lower.contains("use ")
                || lower.contains("run ")
                || lower.contains("do not")
                || lower.contains("don't")
                || lower.contains("follow")
                || lower.contains("ask before");
            if actionable && !rules.contains(&rule.to_string()) && rule.len() <= 180 {
                rules.push(rule.to_string());
            }
        }
    }
    rules
}

fn capitalize(value: &str) -> String {
    let mut chars = value.chars();
    match chars.next() {
        Some(first) => first.to_uppercase().collect::<String>() + chars.as_str(),
        None => String::new(),
    }
}
